@baseurl = http://localhost:8088

###

# @name create
POST {{baseurl}}/create-todo

{
    "title": "Washing up",
    "complete": false
}

###

# @name get
GET {{baseurl}}/get-todo?id={{create.response.body.id}}

###

# @name complete

PUT {{baseurl}}/complete-todo?id={{create.response.body.id}}

###

# @name get
GET {{baseurl}}/get-todo?id={{create.response.body.id}}

###

# @name getAll
GET {{baseurl}}/get-todos?max=50

###

# @name delete
DELETE http://localhost:8088/delete-todo?id={{create.response.body.id}}