apiVersion: apps/v1
kind: Deployment
metadata:
  name: createtodo-depl
  labels:
    app: createtodo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: createtodo
  template:
    metadata:
      labels:
        app: createtodo
    spec:
      containers:
        - name: createtodo
          image: create-todo
          imagePullPolicy: Never
          ports:
            - containerPort: 80
